// biome-ignore-all lint: generated by TanStack Router

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/root";
import { Route as indexRouteImport } from "./routes/index";
import { Route as inviteDotcodeRouteImport } from "./routes/invite.$code";
import { Route as onboardingRouteImport } from "./routes/onboarding";
import { Route as settingsHouseholdMembersRouteImport } from "./routes/settings.household.members";

const indexRoute = indexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const onboardingRoute = onboardingRouteImport.update({
  id: "/onboarding",
  path: "/onboarding",
  getParentRoute: () => rootRouteImport,
} as any);
const settingsHouseholdMembersRoute =
  settingsHouseholdMembersRouteImport.update({
    id: "/settings/household/members",
    path: "/settings/household/members",
    getParentRoute: () => rootRouteImport,
  } as any);
const inviteDotcodeRoute = inviteDotcodeRouteImport.update({
  id: "/invite/$code",
  path: "/invite/$code",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof indexRoute;
  "/onboarding": typeof onboardingRoute;
  "/settings/household/members": typeof settingsHouseholdMembersRoute;
  "/invite/$code": typeof inviteDotcodeRoute;
}
export interface FileRoutesByTo {
  "/": typeof indexRoute;
  "/onboarding": typeof onboardingRoute;
  "/settings/household/members": typeof settingsHouseholdMembersRoute;
  "/invite/$code": typeof inviteDotcodeRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof indexRoute;
  "/onboarding": typeof onboardingRoute;
  "/settings/household/members": typeof settingsHouseholdMembersRoute;
  "/invite/$code": typeof inviteDotcodeRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/onboarding"
    | "/settings/household/members"
    | "/invite/$code";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/onboarding"
    | "/settings/household/members"
    | "/invite/$code";
  id:
    | "__root__"
    | "/"
    | "/onboarding"
    | "/settings/household/members"
    | "/invite/$code";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  indexRoute: typeof indexRoute;
  onboardingRoute: typeof onboardingRoute;
  settingsHouseholdMembersRoute: typeof settingsHouseholdMembersRoute;
  inviteDotcodeRoute: typeof inviteDotcodeRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof indexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/onboarding": {
      id: "/onboarding";
      path: "/onboarding";
      fullPath: "/onboarding";
      preLoaderRoute: typeof onboardingRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings/household/members": {
      id: "/settings/household/members";
      path: "/settings/household/members";
      fullPath: "/settings/household/members";
      preLoaderRoute: typeof settingsHouseholdMembersRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/invite/$code": {
      id: "/invite/$code";
      path: "/invite/$code";
      fullPath: "/invite/$code";
      preLoaderRoute: typeof inviteDotcodeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  indexRoute: indexRoute,
  onboardingRoute: onboardingRoute,
  settingsHouseholdMembersRoute: settingsHouseholdMembersRoute,
  inviteDotcodeRoute: inviteDotcodeRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
